Handle python3-pylint in epylint

diff --git a/epylint b/epylint
--- a/epylint
+++ b/epylint
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-pylint --msg-template='{path}:{line}: {category} ({symbol}): {msg}' \
+
+if [ "$(which pylint 2>/dev/null)" ]; then
+    CMD=pylint
+elif [ "$(which python3-pylint 2>/dev/null)" ]; then
+    CMD=python3-pylint
+else
+    echo '0:0 no-bin (no-bin): failed to find pylint'
+    exit 1
+fi
+
+$CMD --msg-template='{path}:{line}: {category} ({symbol}): {msg}' \
     --reports=n "$@" 2>/dev/null \
     | grep -v ': info'  \
     | sed -r 's/: ([a-z])/: \u\1/' \
